import os
import subprocess
from flask import Flask, render_template, request, redirect, url_for, session, flash, jsonify
from publicsuffix2 import get_sld
import pam
from functools import wraps
from datetime import datetime
import mysql.connector
import pyotp

# Load DB config (generated by install.sh)
from db_config import DB_CONFIG

app = Flask(__name__)
app.secret_key = os.environ.get('FLASK_SECRET', 'supersecretkey')

SQUID_LOG_FILE = "/var/log/squid/access.log"
ALLOW_LIST_FILE = "/etc/squid/allowed_paw.acl"
HIDDEN_LIST_FILE = "/etc/squid/hidden_domains.txt"

# --- MySQL helpers for user/MFA management ---

def get_mysql_conn():
    return mysql.connector.connect(**DB_CONFIG)

def get_user(username):
    with get_mysql_conn() as conn:
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM users WHERE username=%s", (username,))
        return cursor.fetchone()

def get_user_by_id(user_id):
    with get_mysql_conn() as conn:
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM users WHERE id=%s", (user_id,))
        return cursor.fetchone()

def get_all_users():
    with get_mysql_conn() as conn:
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM users")
        return cursor.fetchall()

def add_user(username, email, password, admin_level=0):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO users (username, email, password, admin_level, mfa_enabled) VALUES (%s, %s, PASSWORD(%s), %s, 0)",
            (username, email, password, admin_level)
        )
        conn.commit()

def delete_user(user_id):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("DELETE FROM users WHERE id=%s", (user_id,))
        conn.commit()

def set_user_password(user_id, password):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET password=PASSWORD(%s) WHERE id=%s", (password, user_id))
        conn.commit()

def set_user_admin_level(user_id, admin_level):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET admin_level=%s WHERE id=%s", (admin_level, user_id))
        conn.commit()

def reset_user_mfa(user_id):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET mfa_secret=NULL, mfa_enabled=0 WHERE id=%s", (user_id,))
        conn.commit()

def set_user_mfa(username, secret):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET mfa_secret=%s, mfa_enabled=1 WHERE username=%s", (secret, username))
        conn.commit()

def get_user_mfa(username):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT mfa_secret, mfa_enabled FROM users WHERE username=%s", (username,))
        row = cursor.fetchone()
        return row if row else (None, 0)

def check_user_exists(username):
    with get_mysql_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT username FROM users WHERE username=%s", (username,))
        return cursor.fetchone() is not None

# --- Authentication helpers ---

def is_logged_in():
    return session.get('logged_in', False)

def is_admin():
    return session.get('admin_level', 0) > 0

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not is_logged_in():
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated_function

def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not is_logged_in() or not is_admin():
            flash('Admin access required', 'danger')
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated_function

# --- Allow static files without login ---
@app.before_request
def allow_static_files():
    if request.endpoint and request.endpoint.startswith('static'):
        return

# --- Domain helpers ---

def get_blocked_domains():
    domains = set()
    if os.path.exists(SQUID_LOG_FILE):
        with open(SQUID_LOG_FILE, "r") as f:
            for line in f:
                parts = line.split()
                if len(parts) > 6:
                    domain = parts[6]
                    if domain and not domain.startswith("http:") and not domain.startswith("https:"):
                        domains.add(domain)
    clean_domains = set()
    for domain in domains:
        if ':' in domain:
            domain = domain.split(':')[0]
        if domain.startswith("www."):
            domain = domain[4:]
        clean_domains.add(domain)
    return sorted(clean_domains, key=lambda d: d.lower())

def get_parent_domain(domain):
    parent = get_sld(domain)
    return f".{parent}" if parent and parent != domain else f".{domain}"

def get_allow_list():
    if not os.path.exists(ALLOW_LIST_FILE):
        return []
    with open(ALLOW_LIST_FILE, "r") as f:
        return [line.strip() for line in f if line.strip()]

def get_hidden_list():
    if not os.path.exists(HIDDEN_LIST_FILE):
        return []
    with open(HIDDEN_LIST_FILE, "r") as f:
        return [line.strip() for line in f if line.strip()]

def add_to_allow_list(domain):
    entry = get_parent_domain(domain)
    current = set(get_allow_list())
    if entry not in current:
        with open(ALLOW_LIST_FILE, "a") as f:
            f.write(entry + "\n")
    # Also remove from hidden if present
    remove_from_hidden_list(domain)

def remove_from_allow_list(entry):
    current = set(get_allow_list())
    if entry in current:
        current.remove(entry)
        with open(ALLOW_LIST_FILE, "w") as f:
            for item in sorted(current, key=lambda d: d.lstrip('.').lower()):
                f.write(item + "\n")

def add_to_hidden_list(domain):
    entry = get_parent_domain(domain)
    current = set(get_hidden_list())
    if entry not in current:
        with open(HIDDEN_LIST_FILE, "a") as f:
            f.write(entry + "\n")

def remove_from_hidden_list(domain_or_entry):
    entry = get_parent_domain(domain_or_entry) if not domain_or_entry.startswith('.') else domain_or_entry
    current = set(get_hidden_list())
    if entry in current:
        current.remove(entry)
        with open(HIDDEN_LIST_FILE, "w") as f:
            for item in sorted(current, key=lambda d: d.lstrip('.').lower()):
                f.write(item + "\n")

def mark_changes_pending():
    session["changes_pending"] = True

def clear_changes_pending():
    session.pop("changes_pending", None)

# --- MFA routes ---

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        p = pam.pam()
        if p.authenticate(username, password):
            user = get_user(username)
            if not user:
                flash('User not found in database', 'danger')
                return render_template('login.html')
            secret, enabled = get_user_mfa(username)
            session['pending_user'] = username
            session['pending_admin_level'] = user.get('admin_level', 0)
            if not secret or not enabled:
                return redirect(url_for('mfa_setup'))
            else:
                return redirect(url_for('mfa_verify'))
        else:
            flash('Invalid username or password', 'danger')
    return render_template('login.html')

@app.route('/mfa_setup', methods=['GET', 'POST'])
def mfa_setup():
    username = session.get('pending_user')
    if not username:
        return redirect(url_for('login'))

    if request.method == 'POST':
        secret = session.get('mfa_secret')
        if not secret:
            flash('Session expired. Please try again.', 'danger')
            return redirect(url_for('login'))
        code = request.form['code'].replace(" ", "")
        if not code.isdigit() or len(code) != 6:
            flash('Invalid code format. Enter a 6-digit code from your authenticator app, without spaces.', 'danger')
            qr_uri = pyotp.totp.TOTP(secret).provisioning_uri(username, issuer_name="PAW Proxy Pilot")
            return render_template('mfa_setup.html', secret=secret, qr_uri=qr_uri)
        if pyotp.TOTP(secret).verify(code):
            set_user_mfa(username, secret)
            session['logged_in'] = True
            session['username'] = username
            session['admin_level'] = session.pop('pending_admin_level', 0)
            session.pop('pending_user', None)
            session.pop('mfa_secret', None)
            return redirect(url_for('index'))
        else:
            flash('Invalid MFA code, try again.', 'danger')
            qr_uri = pyotp.totp.TOTP(secret).provisioning_uri(username, issuer_name="PAW Proxy Pilot")
            return render_template('mfa_setup.html', secret=secret, qr_uri=qr_uri)
    else:
        secret = pyotp.random_base32()
        session['mfa_secret'] = secret
        qr_uri = pyotp.totp.TOTP(secret).provisioning_uri(username, issuer_name="PAW Proxy Pilot")
        return render_template('mfa_setup.html', secret=secret, qr_uri=qr_uri)

@app.route('/mfa_verify', methods=['GET', 'POST'])
def mfa_verify():
    username = session.get('pending_user')
    if not username:
        return redirect(url_for('login'))
    secret, enabled = get_user_mfa(username)
    if not secret or not enabled:
        return redirect(url_for('mfa_setup'))
    if request.method == 'POST':
        code = request.form['code'].replace(" ", "")
        if not code.isdigit() or len(code) != 6:
            flash('Invalid code format. Enter a 6-digit code from your authenticator app, without spaces.', 'danger')
            return render_template('mfa_verify.html')
        if pyotp.TOTP(secret).verify(code):
            session['logged_in'] = True
            session['username'] = username
            session['admin_level'] = session.pop('pending_admin_level', 0)
            session.pop('pending_user', None)
            return redirect(url_for('index'))
        else:
            flash('Invalid MFA code, try again.', 'danger')
    return render_template('mfa_verify.html')

@app.route('/logout', methods=['POST', 'GET'])
def logout():
    session.clear()
    return redirect(url_for('login'))

# --- Overview (dashboard) ---

@app.route("/")
@login_required
def index():
    allow_list = get_allow_list()
    hidden_list = get_hidden_list()
    blocked_domains = get_blocked_domains()
    allow_set = set(allow_list)
    hidden_set = set(hidden_list)
    unconfirmed = [d for d in blocked_domains
                   if get_parent_domain(d) not in allow_set and get_parent_domain(d) not in hidden_set]
    clients = {}
    if os.path.exists(SQUID_LOG_FILE):
        with open(SQUID_LOG_FILE, "r") as f:
            for line in f:
                parts = line.split()
                if len(parts) > 2:
                    ip = parts[2]
                    try:
                        timestamp = float(parts[0])
                        last_connected = datetime.utcfromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S')
                    except Exception:
                        last_connected = "Unknown"
                    if ip not in clients or last_connected > clients[ip]:
                        clients[ip] = last_connected

    return render_template(
        "index.html",
        allowed_count=len(allow_list),
        blocked_count=len(hidden_list),
        unconfirmed_count=len(unconfirmed),
        clients=clients,
        page='overview',
        changes_pending=session.get("changes_pending", False)
    )

# --- Manage Allowed Domains ---

@app.route("/manage_allowed", methods=["GET"])
@login_required
def manage_allowed():
    allowed = sorted(get_allow_list(), key=lambda d: d.lstrip('.').lower())
    return render_template(
        "manage_allowed.html",
        allowed_domains=allowed,
        page='allowed',
        show_bulk=True,
        changes_pending=session.get("changes_pending", False)
    )

@app.route("/add_allowed_domain", methods=["POST"])
@login_required
def add_allowed_domain():
    domain = request.form.get("domain")
    if domain:
        add_to_allow_list(domain)
        mark_changes_pending()
    return redirect(url_for("manage_allowed"))

@app.route("/remove_allowed_domain", methods=["POST"])
@login_required
def remove_allowed_domain():
    entry = request.form.get("domain") or request.form.get("entry")
    if entry:
        remove_from_allow_list(entry)
        mark_changes_pending()
    return redirect(url_for("manage_allowed"))

@app.route("/bulk_remove_allowed", methods=["POST"])
@login_required
def bulk_remove_allowed():
    selected = request.form.getlist('selected_domains')
    for entry in selected:
        remove_from_allow_list(entry)
    mark_changes_pending()
    return redirect(url_for("manage_allowed"))

# --- Manage Blocked Domains ---

@app.route("/manage_blocked", methods=["GET"])
@login_required
def manage_blocked():
    blocked = sorted(get_hidden_list(), key=lambda d: d.lstrip('.').lower())
    return render_template(
        "manage_blocked.html",
        blocked_domains=blocked,
        page='blocked',
        show_bulk=True,
        changes_pending=session.get("changes_pending", False)
    )

@app.route("/add_blocked_domain", methods=["POST"])
@login_required
def add_blocked_domain():
    domain = request.form.get("domain")
    if domain:
        add_to_hidden_list(domain)
        mark_changes_pending()
    return redirect(url_for("manage_blocked"))

@app.route("/remove_blocked_domain", methods=["POST"])
@login_required
def remove_blocked_domain():
    entry = request.form.get("domain") or request.form.get("entry")
    if entry:
        remove_from_hidden_list(entry)
        mark_changes_pending()
    return redirect(url_for("manage_blocked"))

@app.route("/bulk_remove_blocked", methods=["POST"])
@login_required
def bulk_remove_blocked():
    selected = request.form.getlist('selected_domains')
    for entry in selected:
        remove_from_hidden_list(entry)
    mark_changes_pending()
    return redirect(url_for("manage_blocked"))

# --- Manage Unsorted Domains ---

@app.route("/manage_unsorted", methods=["GET"])
@login_required
def manage_unsorted():
    allow_set = set(get_allow_list())
    hidden_set = set(get_hidden_list())
    blocked_domains = get_blocked_domains()
    unsorted = []
    for domain in blocked_domains:
        parent = get_parent_domain(domain)
        if parent not in allow_set and parent not in hidden_set:
            unsorted.append(domain)
    unsorted = sorted(set(unsorted), key=lambda d: d.lower())
    return render_template(
        "manage_unsorted.html",
        unsorted_domains=unsorted,
        page='unsorted',
        show_bulk=True,
        changes_pending=session.get("changes_pending", False)
    )

@app.route("/mark_allowed", methods=["POST"])
@login_required
def mark_allowed():
    domain = request.form.get("domain")
    if domain:
        add_to_allow_list(domain)
        mark_changes_pending()
    return redirect(url_for("manage_unsorted"))

@app.route("/mark_blocked", methods=["POST"])
@login_required
def mark_blocked():
    domain = request.form.get("domain")
    if domain:
        add_to_hidden_list(domain)
        mark_changes_pending()
    return redirect(url_for("manage_unsorted"))

@app.route("/bulk_mark_unsorted", methods=["POST"])
@login_required
def bulk_mark_unsorted():
    selected = request.form.getlist('selected_domains')
    bulk_action = request.form.get('bulk')
    if bulk_action == 'allow':
        for domain in selected:
            add_to_allow_list(domain)
    elif bulk_action == 'block':
        for domain in selected:
            add_to_hidden_list(domain)
    mark_changes_pending()
    return redirect(url_for("manage_unsorted"))

# --- Squid Restart and Clear Changes ---

@app.route("/restart_squid", methods=["POST"])
@login_required
def restart_squid():
    try:
        if request.headers.get("X-Requested-With") == "XMLHttpRequest":
            result = subprocess.run(
                ["/usr/bin/systemctl", "restart", "squid"],
                capture_output=True, text=True
            )
            if result.returncode != 0:
                return jsonify({"status": "Error restarting Squid: " + result.stderr}), 500
            status = subprocess.run(
                ["/usr/bin/systemctl", "is-active", "squid"],
                capture_output=True, text=True
            )
            if status.stdout.strip() != "active":
                return jsonify({"status": "Squid did not start successfully: " + status.stdout + status.stderr}), 500
            clear_changes_pending()
            return jsonify({"status": "Squid restarted successfully."})
        result = subprocess.run(
            ["/usr/bin/systemctl", "restart", "squid"],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            return f"Error restarting squid:<br><pre>{result.stderr}</pre>", 500
        status = subprocess.run(
            ["/usr/bin/systemctl", "is-active", "squid"],
            capture_output=True, text=True
        )
        if status.stdout.strip() != "active":
            return f"Squid did not start successfully.<br><pre>{status.stdout} {status.stderr}</pre>", 500
        clear_changes_pending()
        return redirect(url_for("index"))
    except Exception as e:
        return f"Exception: {e}", 500

@app.route("/clear_changes", methods=["POST"])
@login_required
def clear_changes():
    clear_changes_pending()
    return redirect(request.referrer or url_for("index"))

@app.route("/admin")
@login_required
def admin():
    # You can add logic here for admin-only checks if needed
    return render_template("admin.html")

# --- User management (ADMIN ONLY) ---

@app.route('/admin/users')
@admin_required
def admin_users():
    users = get_all_users()
    return render_template('admin_users.html', users=users)

@app.route('/admin/users/add', methods=['GET', 'POST'])
@admin_required
def admin_users_add():
    if request.method == 'POST':
        username = request.form['username'].strip()
        email = request.form['email'].strip()
        password = request.form['password']
        admin_level = int(request.form.get('admin_level', 0))
        if not username or not email or not password:
            flash('All fields are required.', 'danger')
            return redirect(url_for('admin_users_add'))
        if check_user_exists(username):
            flash('Username already exists.', 'danger')
            return redirect(url_for('admin_users_add'))
        add_user(username, email, password, admin_level)
        flash('User added.', 'success')
        return redirect(url_for('admin_users'))
    return render_template('admin_users_add.html')

@app.route('/admin/users/<int:user_id>/delete', methods=['POST'])
@admin_required
def admin_users_delete(user_id):
    user = get_user_by_id(user_id)
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for('admin_users'))
    # Don't let admin delete themselves
    if session.get("username") == user.get('username'):
        flash("You cannot delete yourself.", "danger")
        return redirect(url_for('admin_users'))
    delete_user(user_id)
    flash("User deleted.", "success")
    return redirect(url_for('admin_users'))

@app.route('/admin/users/<int:user_id>/reset_password', methods=['GET', 'POST'])
@admin_required
def admin_users_reset_password(user_id):
    user = get_user_by_id(user_id)
    if not user:
        flash('User not found.', 'danger')
        return redirect(url_for('admin_users'))
    if request.method == 'POST':
        password = request.form['password']
        if not password:
            flash('Password required.', 'danger')
            return redirect(url_for('admin_users_reset_password', user_id=user_id))
        set_user_password(user_id, password)
        flash('Password reset.', 'success')
        return redirect(url_for('admin_users'))
    return render_template('admin_users_reset_password.html', user=user)

@app.route('/admin/users/<int:user_id>/set_admin_level', methods=['POST'])
@admin_required
def admin_users_set_admin_level(user_id):
    admin_level = int(request.form.get('admin_level', 0))
    set_user_admin_level(user_id, admin_level)
    flash('Admin level updated.', 'success')
    return redirect(url_for('admin_users'))

@app.route('/admin/users/<int:user_id>/reset_mfa', methods=['POST'])
@admin_required
def admin_users_reset_mfa(user_id):
    reset_user_mfa(user_id)
    flash('User MFA reset.', 'success')
    return redirect(url_for('admin_users'))

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
